### PR TITLE
fix: improve genei and shippori fonts

### PR DESCRIPTION
**Pull request by KojoZero**
Greatly improves the font rendering of Genei Koburi Mincho and Shippori Mincho on Windows PCs and lower resolution devices. Along with that, changed the name from "Genei Koburi Mincho v5" to "Genei Koburi Mincho" since v5 refers to the release version.

### CODE REVIEW

**Comment by Renji-XD** [comment]
Hi,

ty for your pr. The font key name change is actually a (temporary) breaking one - if someone used genei before it would actually fail and load a fallback system font until settings are changed as the name. Also - while being an edge case - if someone have created a custom variant via userfont with that name it would now clash too.

I guess you could check if the old value is used and map it to the new one but tbh i would simply leave it as is and just replace the font files

**Comment by KojoZero** [comment]
I've updated the pr back to the original Genei name to avoid the potential issues.

**Comment by KojoZero** [comment]
Also the Genei Koburi Mincho version used is outdated and the latest version is v6.1a. I wasn't sure if it was intentional to use the v5 version so I left it, but I could update it to v6.1 and add it to the pr.

**Comment by Renji-XD** [comment]
the original list is based on a discord post and the author liked v5 more. If someone wants to compare/use a different one they can always load it via userfont feature (which did not existed back then)

**Pull request merged**
