### PR TITLE
[feat] add grayish mode

### PR DESCRIPTION
**Pull request by Renji-XD**
I personally find the current dark theme too strong in terms of contrast

PR adds a gray theme (same vars as dark, just a different background-color) similar to a color tone of the dark mode of the edge browser.

https://imgur.com/a/8EIfgMK

### CODE REVIEW

**Comment by wizo06** [comment]
May I suggest the gray background from Discord's dark theme.
```css
-background-color: #23272a;
--font-color: #e3e3e3;
```
(taken directly from Discord's brand guidelines)

**Comment by Renji-XD** [comment]
here for ccomparison
https://imgur.com/a/iXWHXnX

1) as is
2) your suggestion
3) background color of your suggestion but font-color of dark-theme

Not sure if my eyes are simply already like the ones of a 70 year old man or its the font size or whatever.. but the font of 2 is really kind of glowing compared to the other ones to me.. could imagine my eyes would hurt after a some time.

BG would be ok for me even if it goes again more in a dark (blue) direction rather than gray/brown.. or adding both (not sure if for that differences are worth it)

**Comment by ttu-ttu** [comment]
@wizo06 what do you think for 3?

@Renji-XD what if the font color has 87% opacity?

Also, I would prefer the new theme to be in between light and dark theme (for the array), and use hexadecimal code for color if it doesn't include alpha value

**Comment by Renji-XD** [comment]
https://imgur.com/a/utx3rHk

1) 1.0
2) 0.87
3) 0.8
4) only bg, rest from dark

https://imgur.com/a/LrsCGx9

0.87 is relatively ok, maybe still a bit glowing on "hide furiga". 0.8 looks at first glance a bit better to me personally but both would be fine i guess. So rgba(227, 227, 227, 0.87 or 0.8) + the order change it is i guess

**Comment by ttu-ttu** [comment]
Yeah let's go for `#23272a` + 0.8 opacity font, with the orders updated

**Comment by Renji-XD** [comment]
@ttu-ttu done

**Pull request merged**
