### PR TITLE
Update on docker-compose.yml

### PR DESCRIPTION
**Pull request by victormatheusEK**
- Changed the default port of the container, because it was currently using the default port for proxies, which was causing conflict with proxy applications like burpsuite.
- Added new command to make the container always restart if stopped unexpectedly (like power outage).

I tested on my machine and it is working well on port 9010

### CODE REVIEW

**Comment by Renji-XD** [comment]
Hey, could you also update the respective part in the readme to be aligned - ty

**Comment by victormatheusEK** [comment]
@Renji-XD Oh, sorry, forgot about it. Do you want me to also update the docker part or only the docker-compose one? Because with the docker command, the user can set any port they want, so i'm not sure if I should update

**Comment by Renji-XD** [comment]
@victormatheusEK i think the compose part is good enough - think there are anyways not many users actually using it and are otherwise tech savvy enough : )

**Comment by victormatheusEK** [comment]
@Renji-XD Done. Thank you for you hard work!

**Pull request merged**
